### ISSUE TITLE
GN 2.12.0 Erreur serveur 500 - Synchronisation des données

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_mobile_occtax#215]
### Version de l'application

Version d'Occtax-mobile affectée par le bug : 2.5.0
Version de GeoNature utilisée : 2.12.0

Bonjour à tous,

### Terminal et Version Android

Marque et modèle du terminal : Samsung Galaxy Tab S8
Version d'Android : 13

### Description du bug et comportement attendu
`INTERNAL SERVER ERROR` lors du `DataSyncWorker` sur l'api `geonature/api/meta/datasets?fields=modules`

### Comment reproduire
Le `CRUVED` du module `OCCTAX` n'est pas hérité du module parent `GEONATURE` et une des lettres a une valeur différente de 3.
Cette erreur est peut-être en lien avec https://github.com/PnX-SI/GeoNature/issues/2454#top

### Logs
- Logs `/Android/data/fr.geonature.occtax2`
``` android
15:39:24.893 INFO: [fr.geonature.datasync.sync.DataSyncViewModel] starting local data synchronization...
15:39:24.923 INFO: [fr.geonature.datasync.api.ClientKt] --> GET https://geonature.cen-isere.fr/geonature/api/gn_commons/t_mobile_apps
15:39:24.925 INFO: [fr.geonature.datasync.packageinfo.PackageInfoRepositoryImpl] updating settings for 'fr.geonature.occtax2'...
15:39:24.928 INFO: [fr.geonature.datasync.packageinfo.io.AppSettingsJsonWriter] updating app settings '/storage/emulated/0/Android/data/fr.geonature.occtax2/settings_occtax.json'
15:39:24.947 INFO: [fr.geonature.datasync.sync.usecase.DataSyncUseCase] starting local data synchronization from 'https://geonature.cen-isere.fr/geonature' (with additional data: true)...
15:39:24.951 INFO: [fr.geonature.datasync.packageinfo.worker.InputsSyncWorker] no observation records to synchronize for 'fr.geonature.occtax2'
15:39:24.953 INFO: [fr.geonature.datasync.sync.usecase.DataSyncUseCase] synchronize dataset...
15:39:24.956 INFO: [fr.geonature.datasync.api.ClientKt] --> GET https://geonature.cen-isere.fr/geonature/api/meta/datasets?fields=modules
15:39:25.069 INFO: [fr.geonature.datasync.api.ClientKt] <-- 200 OK https://geonature.cen-isere.fr/geonature/api/gn_commons/t_mobile_apps (144ms, unknown-length body)
15:39:30.697 INFO: [fr.geonature.datasync.api.ClientKt] <-- HTTP FAILED: InternalServerException(message=INTERNAL SERVER ERROR, response=Response{protocol=http/1.1, code=500, message=INTERNAL SERVER ERROR, url=https://geonature.cen-isere.fr/geonature/api/meta/datasets?fields=modules}, cause=null)
15:39:30.716 WARN: [fr.geonature.datasync.sync.worker.DataSyncWorker] INTERNAL SERVER ERROR: fr.geonature.datasync.api.error.BaseApiException$InternalServerException: INTERNAL SERVER ERROR
    at fr.geonature.datasync.api.ClientKt$createServiceClient$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1098)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
15:39:30.718 INFO: [fr.geonature.datasync.sync.worker.DataSyncWorker] local data synchronization finished with failed tasks in 5779ms
15:46:44.561 INFO: [fr.geonature.datasync.packageinfo.worker.CheckInputsToSynchronizeWorker] available inputs to synchronize: 0
```
- Logs `/var/log/geonature/geonature.log`
``` py
[2023-04-04 15:39:25 +0200] [2525] [ERROR] Exception on /meta/datasets [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 18, in decorated_view
    return view_func(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_meta/routes.py", line 155, in get_datasets
    return dataset_schema.jsonify(query.all(), many=True)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask_marshmallow/schema.py", line 39, in jsonify
    data = self.dump(obj, many=many)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 560, in dump
    result = self._invoke_dump_processors(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 1068, in _invoke_dump_processors
    data = self._invoke_processors(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 1215, in _invoke_processors
    data = [
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 1216, in <listcomp>
    processor(item, original, many=many, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_meta/schemas.py", line 74, in module_input
    if not original.has_instance_permission(create_scope):
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_meta/models.py", line 533, in has_instance_permission
    return _through_af and self.acquisition_framework.has_instance_permission(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 728, in get
    value = callable_(state, passive)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 969, in __call__
    return strategy._load_for_state(state, passive)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 710, in _load_for_state
    self._invoke_raise_load(state, passive, "raise")
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 671, in _invoke_raise_load
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: 'TDatasets.acquisition_framework' is not available due to lazy='raise'
```
Merci pour vos retours

**Comment by camillemonchicourt** [comment]
OK OK.
Pas de chance décidément ! 🤔

Pourtant on a pas mal testé la version 2.12.0 dans tous les sens, dont son usage avec Occtax-mobile avant de la sortir.
Et Occtax-mobile a bien fonctionné avec la future version 2.12.0 de GeoNature lors de nos tests.

Mais il y a des cas qu'on ne devait pas avoir et pour lesquels on est donc passé au travers.

On va regarder ces différents retours dès que possible pour sortir une version corrective 2.12.1 dans la semaine prochaine.

**Comment by camillemonchicourt** [comment]
Le message d'erreur semble en effet similaire à https://github.com/PnX-SI/GeoNature/issues/2454

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 2.12.1 de GeoNature.
